# File and Folder
alias md='mkdir -p'
alias rd=rmdir
alias delete='sudo rm -rf'



# Listings
alias home='cd ~' 
alias cls= 'clear; ls'
alias ls='ls -hF --color'
alias ll='ls -l'
alias sl= 'ls'
alias sls='ls'
alias kk=ll
alias lo='ls -l | sed -e 's/--x/1/g' -e 's/-w-/2/g' -e 's/-wx/3/g' -e 's/r--/4/g' -e 's/r-x/5/g' -e 's/rw-/6/g' -e 's/rwx/7/g' -e 's/---/0/g''
alias cd..='cd ..'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
